name: Отчет о баге
description: Сообщите об ошибках или непредвиденном поведении в приложении Laney.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **Спасибо за ваш отчет об ошибках в приложении Laney!**

        Чтобы нам было легче помочь вам, пожалуйста, заполните всю подробную информацию ниже.
  - type: textarea
    attributes:
      label: Шаги для воспроизведения
      description: |
        Опишите пошагово действия, которые привели к возникновению проблемы. 
        Чем точнее и детальнее будет описание, тем быстрее мы сможем воспроизвести ошибку и найти её причину.

        Пример:
        1. Откройте приложение и перейдите в раздел "Настройки".
        2. Измените параметр "Тема" на "Тёмная".
        3. Перезагрузите приложение и обратите внимание на ошибку.
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Фактический результат
      description: |
        Опишите, что произошло на самом деле после выполнения шагов. Какие ошибки или некорректное поведение вы заметили?
        Это может быть сообщение об ошибке, некорректное отображение интерфейса или сбой в работе функции.

        Пример:
        После изменения темы приложение не запускается и показывает сообщение об ошибке "Critical failure".
      placeholder: Опишите, что произошло на самом деле
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ожидаемый результат
      description: |
        Опишите, что вы ожидали увидеть после выполнения шагов. Какое поведение или результат вы считаете правильным и соответствующим ожиданиям?

        Пример:
        Ожидалось, что приложение изменит тему на "Тёмная" и продолжит работать корректно.
      placeholder: Опишите, что должно было произойти
    validations:
      required: true
  - type: input
    attributes:
      label: Операционная система
      description: |
        Укажите название и точную версию вашей операционной системы. Это важно для анализа совместимости и возможных системных конфликтов.

        **Важно:** Не указывайте версию ядра (например, `uname` на Linux), она не предоставляет полезной информации для отладки.
        
        Пример: Windows 11 Pro, версия 23H2
    validations:
      required: true
  - type: input
    attributes:
      label: Версия приложения Laney
      description: |
        Укажите точную версию приложения Laney, которую вы используете. Это помогает нам понять, в какой версии возникла проблема.

        **Не используйте общее "последняя версия" или "не знаю".** Проверьте точную версию в настройках приложения.

        Пример: Версия 1.4.3
    validations:
      required: true
  - type: textarea
    attributes:
      label: Вложения (скриншоты)
      description: |
        Прикрепите скриншоты, если они помогут визуализировать проблему. Скриншоты могут быть особенно полезны при визуальных ошибках или для демонстрации сообщений об ошибке.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Логи
      description: >
        Если возможно, приложите файл log.txt, чтобы помочь нам в диагностике проблемы.
      placeholder: Вставьте здесь содержимое log.txt (если необходимо)
      render: shell
